[project]
name = "rpt2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "safetensors>=0.5.2",
    "tiktoken>=0.8.0",
    "torch>=2.5.1",
]
